//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Cart_id { get; set; }
        public Nullable<int> U_id { get; set; }
        public string P_id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
