//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int I_id { get; set; }
        public string P_id { get; set; }
        public Nullable<int> Is_Main { get; set; }
        public string Image_name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
