//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reset_Password_request
    {
        public string Id { get; set; }
        public Nullable<int> U_id { get; set; }
        public Nullable<System.DateTime> Requested_Date { get; set; }
    }
}
